# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-24 18:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
        ('metrics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fitness',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date', models.DateTimeField()),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Human')),
            ],
        ),
    ]
