# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-02 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0003_auto_20170725_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fitness',
            name='m_date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='weighs',
            name='m_date',
            field=models.DateTimeField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='weighs',
            name='weigh',
            field=models.FloatField(verbose_name='Вес, кг'),
        ),
    ]
