# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 17:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_flowmeter'),
        ('metrics', '0004_auto_20170802_0627'),
    ]

    operations = [
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date', models.DateTimeField(verbose_name='Дата')),
                ('indicate', models.IntegerField(verbose_name='Показания')),
                ('flowmeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Flowmeter')),
            ],
        ),
    ]
