# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0005_indication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='indicate',
            field=models.FloatField(verbose_name='Показания'),
        ),
    ]
