# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-05 18:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_flowmeter'),
        ('metrics', '0006_auto_20170805_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='Communal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_date', models.DateTimeField(verbose_name='Дата')),
                ('tarif', models.FloatField(verbose_name='Тариф')),
                ('flowmeter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Flowmeter')),
            ],
        ),
    ]
