# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0007_communal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weighs',
            options={'verbose_name': 'Weighs'},
        ),
    ]
