# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-29 18:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('metrics', '0008_auto_20170829_2115'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fitness',
            options={'verbose_name': 'Fitness'},
        ),
    ]
