# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-20 07:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0002_flowmeter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Human_Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weigh_th', models.FloatField(verbose_name='Вес, кг')),
                ('human', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Human')),
            ],
        ),
    ]
