# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-21 03:07
from __future__ import unicode_literals

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0003_human_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='human_settings',
            name='weigh_th',
        ),
        migrations.AddField(
            model_name='human_settings',
            name='c_date',
            field=models.DateTimeField(default=timezone.now(), verbose_name='Дата'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human_settings',
            name='set_name',
            field=models.CharField(default=' ', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='human_settings',
            name='set_val',
            field=models.CharField(default=' ', max_length=250),
            preserve_default=False,
        ),
    ]
